### ISSUE TITLE
Prestige does not reward you with anything

### ISSUE THREAD

**Issue by chutz747** [spotky1004/Resource-Grid#10]
playing game here.

https://spotky1004.com/Resource-Grid/

I am owed a whole bunch of shards. Is there any way to modify save to add them in?

**Comment by spotky1004** [comment]
```js
let data = JSON.parse(localStorage.resource_grid);
data.resources[73].have += +data.prestige.lastPrestigeResourceQuantity;
localStorage.setItem('resource_grid', JSON.stringify(data));
setTimeout(() => location.reload(), 0);
```

**Comment by baconsplit** [comment]
Just wanted to add to this that I also didn't receive any Shards for a 501 powder prestige. My first 50 powder prestige worked just fine
