### ISSUE TITLE
Empowering boost tiles doesn't increase their power.

### ISSUE THREAD

**Issue by Natsu675** [spotky1004/Resource-Grid#12]
I don't know if they're supposed the be able to be empowered, but since you can, they should give a boost, or remove them from the empowering tab.
It says that the effect is multiplied, but it only reduces the time it takes.

**Comment by spotky1004** [comment]
I already did that. Wait for the next update

**Comment by Natsu675** [comment]
Sorry I posted two times, you responded so quickly I thought I hadn't written it, my apologies
