### ISSUE TITLE
Core drop rate plummeted 

### ISSUE THREAD

**Issue by hobocop2016** [spotky1004/Resource-Grid#13]
Cores had a good drop rate at first but I think after buying a bunch of Gem Boost upgrades it got worse.

![image](https://user-images.githubusercontent.com/20385952/135901990-bca6e40c-8ac5-48f1-aa64-267b654068f4.png)

**Comment by spotky1004** [comment]
fixed!
https://github.com/spotky1004/Resource-Grid/commit/9e437eab226451f3b309f2fa3cbe91838a20eb04
