### ISSUE TITLE
Cores only update on tab switch

### ISSUE THREAD

**Issue by nboehret** [spotky1004/Resource-Grid#16]
Hello,

Once my shiny stone per second was to the point where Core was showing a percent and not a ratio I started to notice that my core number should be updating but was not. I tried a lot to get it to work but only once I came here to look if someone had reported a bug I saw that when I switched back to the game tab the number updated. What really sucks is it only goes up by one this way and does not seem to 'bank' how much should've been gained in this time.

I love the game, great job!

**Comment by spotky1004** [comment]
Fixed!
https://github.com/spotky1004/Resource-Grid/commit/9e437eab226451f3b309f2fa3cbe91838a20eb04
