### ISSUE TITLE
Uncaught DOMException: The quota has been exceeded.

### ISSUE THREAD

**Issue by nsatter** [spotky1004/Resource-Grid#4]
Loving the game but ran into a fatal issue. From a quick search it looks like it is trying to save too much to local storage. Here is the full error message and save game info. 

```Uncaught DOMException: The quota has been exceeded. main.e6fa6888.chunk.js:1
    We saveload.js:15
    We tick.js:18
    39 index.js:20
    (Async: setInterval handler)
    39 index.js:20
    i (index):1
    r (index):1
    t (index):1
    <anonymous> main.e6fa6888.chunk.js:1```

[save info.txt](https://github.com/spotky1004/Resource-Grid/files/7206994/save.info.txt)

**Comment by spotky1004** [comment]
I didn't even know there's a limit in localStorage... I'll try to fix that!

**Comment by spotky1004** [comment]
I wonder what browser you're using.
It looks like localStorage has 5MB of storage in my browser. (I'm using Chrome)

**Comment by nsatter** [comment]
Firefox. From https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria
Looks like it is dynamic based on disk size and total usage. 
Looks like it may have been a red herring anyway. Here are the numbers from Resource Grid { quota: 1505755136, usage: 5308411 }

**Comment by tristo7** [comment]
Seeing this in Firefox still, taken from console logs today:

```
Uncaught DOMException: The quota has been exceeded. main.5565362a.chunk.js:1
    f saveload.js:41
    Kn tick.js:22
    41 index.js:20
    (Async: setInterval handler)
    41 index.js:20
    i (index):1
    r (index):1
    t (index):1
    <anonymous> main.5565362a.chunk.js:1
```
