### ISSUE TITLE
Offline Coal and Glass production

### ISSUE THREAD

**Issue by Karthas077** [spotky1004/Resource-Grid#5]
Despite running obvious net-positive on coal and glass (Within minutes of launching the page I'll have a few thousand coal and a few hundred glass), a short amount of offline production results in me loading into the game with 0 of each, and often 0 of a few dependent crafts (such as traps and houses). It seems like I'm still getting Loot production as if traps/animals had been successfully crafted while offline but it's really hard to tell if it's as many as I'm supposed to have.

**Comment by spotky1004** [comment]
I think it's problem of offline progress.

The offline progress tick is computed at once.
-> automate works from top-left from right only once.
-> Trap is located higher than Glass.
-> Trap didn't calculate with new Glass quantity.

I think I can fix this issue by calculating offline progress in splitted small parts.

**Comment by Karthas077** [comment]
Ah that could also explain why the coal vanishes. By the time it comes Lava's turn to produce, it's been reduced to 0, so instead of 3 coal per lava, the cost is now 50 each, and because it's one big batch, it's not getting the incremental discount.
