### ISSUE TITLE
Less energy than expected during online play

### ISSUE THREAD

**Issue by Karthas077** [spotky1004/Resource-Grid#6]
My energy production is advertised as 1.02k/s, yet it takes me ~2-3 seconds to make 1k energy. I don't think it's a game tick issue because timing 30s build times shows they're finishing in exactly 30 seconds.

A VERY loose testing of offline progress seems to indicate energy is gained at the "correct" rate while offline.

**Comment by spotky1004** [comment]
Fixed!
https://github.com/spotky1004/Resource-Grid/commit/a0e660318e98229f390bcff4aa895b8624aafaae

**Comment by Karthas077** [comment]
Awesome! Thank you! Loving the fast updates and response times. Keep up the good work!
