### ISSUE TITLE
Displayed produced amount does not match amount produced.

### ISSUE THREAD

**Issue by TimWherry** [spotky1004/Resource-Grid#9]
Example: In this gif it shows that it should take less than 2 seconds to produce 1,000 energy, but it takes closer to 5 seconds.

![toolong](https://user-images.githubusercontent.com/7514671/135181841-7e184c4a-9dd6-4996-80dd-490fab464280.gif)

**Comment by Karthas077** [comment]
It's most noticeable for lava production/consumption for me. According to my gem's production display they should be consuming 11.07, 16.6, 19.92, and 22.132 lava each, for a total of 69.722 lava per second. The tooltip for my lava shows it as producing 193.7, or just shy of 3x as much. Despite this, during active play my lava amount is visibly trending downards.

**Comment by spotky1004** [comment]
I fixed this bug, wait for next update!
